//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1573, 1591

using System;
using System.Collections.Generic;
using System.Linq;

using LinqToDB;
using LinqToDB.Configuration;
using LinqToDB.Mapping;

namespace Athena.Models
{
	/// <summary>
	/// Database       : athena
	/// Data Source    : athena
	/// Server Version : 3.42.0
	/// </summary>
	public partial class AthenaDb : LinqToDB.Data.DataConnection
	{
		public ITable<Download>     Downloads     { get { return this.GetTable<Download>(); } }
		public ITable<DownloadTask> DownloadTasks { get { return this.GetTable<DownloadTask>(); } }
		public ITable<Exchange>     Exchanges     { get { return this.GetTable<Exchange>(); } }
		public ITable<Link>         Links         { get { return this.GetTable<Link>(); } }
		public ITable<Schedule>     Schedules     { get { return this.GetTable<Schedule>(); } }
		public ITable<VwAllData>    VwAllData     { get { return this.GetTable<VwAllData>(); } }

		public AthenaDb()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public AthenaDb(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public AthenaDb(DataOptions options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public AthenaDb(DataOptions<AthenaDb> options)
			: base(options.Options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();
	}

	[Table("Downloads")]
	public partial class Download
	{
		[PrimaryKey, Identity   ] public long     Id         { get; set; } // integer
		[Column,     NotNull    ] public long     LinkId     { get; set; } // integer
		[Column,        Nullable] public string   SourceLink { get; set; } // string(max)
		[Column,        Nullable] public string   Status     { get; set; } // string(max)
		[Column,     NotNull    ] public DateTime At         { get; set; } // datetime

		#region Associations

		/// <summary>
		/// FK_Downloads_0_0 (Links)
		/// </summary>
		[Association(ThisKey="LinkId", OtherKey="Id", CanBeNull=false)]
		public Link Link { get; set; }

		#endregion
	}

	[Table("DownloadTasks")]
	public partial class DownloadTask
	{
		[PrimaryKey, Identity   ] public long   Id         { get; set; } // integer
		[Column,     NotNull    ] public string Name       { get; set; } // string(max)
		[Column,        Nullable] public long?  LinkId     { get; set; } // integer
		[Column,        Nullable] public long?  ExchangeId { get; set; } // integer

		#region Associations

		/// <summary>
		/// FK_DownloadTasks_0_0 (Links)
		/// </summary>
		[Association(ThisKey="LinkId", OtherKey="Id", CanBeNull=true)]
		public Link Link { get; set; }

		#endregion
	}

	[Table("Exchanges")]
	public partial class Exchange
	{
		[PrimaryKey, Identity] public long   Id   { get; set; } // integer
		[Column,     NotNull ] public string Name { get; set; } // string(max)
	}

	[Table("Links")]
	public partial class Link
	{
		[PrimaryKey, Identity] public long   Id                { get; set; } // integer
		[Column,     NotNull ] public string Name              { get; set; } // string(max)
		[Column,     NotNull ] public string SourceURL         { get; set; } // string(max)
		[Column,     NotNull ] public string FormattedURL      { get; set; } // string(max)
		[Column,     NotNull ] public string Destination       { get; set; } // string(max)
		[Column,     NotNull ] public string DestinationFormat { get; set; } // string(max)

		#region Associations

		/// <summary>
		/// FK_Downloads_0_0_BackReference (Downloads)
		/// </summary>
		[Association(ThisKey="Id", OtherKey="LinkId", CanBeNull=true)]
		public IEnumerable<Download> Downloads { get; set; }

		/// <summary>
		/// FK_DownloadTasks_0_0_BackReference (DownloadTasks)
		/// </summary>
		[Association(ThisKey="Id", OtherKey="LinkId", CanBeNull=true)]
		public IEnumerable<DownloadTask> DownloadTasks { get; set; }

		#endregion
	}

	[Table("Schedules")]
	public partial class Schedule
	{
		[PrimaryKey, Identity] public long   Id   { get; set; } // integer
		[Column,     NotNull ] public string Name { get; set; } // string(max)
	}

	[Table("vwAllData", IsView=true)]
	public partial class VwAllData
	{
		[Column(),           Identity   ] public long     Id                { get; set; } // integer
		[Column(),           NotNull    ] public string   Name              { get; set; } // string(max)
		[Column(),              Nullable] public long?    LinkId            { get; set; } // integer
		[Column(),              Nullable] public long?    ExchangeId        { get; set; } // integer
		[Column("Id:1"),     Identity   ] public long     Id1               { get; set; } // integer
		[Column("Name:1"),   NotNull    ] public string   Name1             { get; set; } // string(max)
		[Column(),           NotNull    ] public string   SourceURL         { get; set; } // string(max)
		[Column(),           NotNull    ] public string   FormattedURL      { get; set; } // string(max)
		[Column(),           NotNull    ] public string   Destination       { get; set; } // string(max)
		[Column(),           NotNull    ] public string   DestinationFormat { get; set; } // string(max)
		[Column("Id:2"),     Identity   ] public long     Id2               { get; set; } // integer
		[Column("Name:2"),   NotNull    ] public string   Name2             { get; set; } // string(max)
		[Column("Id:3"),     Identity   ] public long     Id3               { get; set; } // integer
		[Column("LinkId:1"), NotNull    ] public long     LinkId1           { get; set; } // integer
		[Column(),              Nullable] public string   SourceLink        { get; set; } // string(max)
		[Column(),              Nullable] public string   Status            { get; set; } // string(max)
		[Column(),           NotNull    ] public DateTime At                { get; set; } // datetime
	}

	public static partial class TableExtensions
	{
		public static Download Find(this ITable<Download> table, long Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static DownloadTask Find(this ITable<DownloadTask> table, long Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static Exchange Find(this ITable<Exchange> table, long Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static Link Find(this ITable<Link> table, long Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static Schedule Find(this ITable<Schedule> table, long Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}
	}
}
