<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Models\Download.cs" />
    <Compile Remove="Models\DownloadTask.cs" />
    <Compile Remove="Models\Exchange.cs" />
    <Compile Remove="Models\Link.cs" />
    <Compile Remove="Models\Schedule.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="AthenaUseCase.txt" />
    <None Remove="msn.ico" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="AthenaUseCase.txt" />
    <Content Include="msn.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AngleSharp" Version="1.1.2" />
    <PackageReference Include="CsvHelper" Version="33.0.1" />
    <PackageReference Include="DotNetZip" Version="1.16.0" />
    <PackageReference Include="linq2db" Version="5.4.1" />
    <PackageReference Include="linq2db.SQLite" Version="5.4.1" />
    <PackageReference Include="Mapster" Version="7.4.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Database\athena.db">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Models\AthenaDb.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>AthenaDb.generated.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Models\AthenaDb.generated.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>AthenaDb.tt</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>